# Getting Started with Numpy

In [1]:
import numpy as np

In [2]:
print("Numpy has begun...")

Numpy has begun...


In [3]:
myarr = np.array([[3,6,37,7]],np.int64)

In [4]:
myarr


array([[ 3,  6, 37,  7]])

In [5]:
print(myarr[0,1])

6


In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,1] = 45

In [9]:
myarr

array([[ 3, 45, 37,  7]])

In [10]:
print(myarr)

[[ 3 45 37  7]]


# Array Creation : Conversion from other Python Structures

In [11]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
print(listarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
listarray.dtype


dtype('int64')

In [14]:
listarray.size

9

In [15]:
listarray.shape

(3, 3)

In [16]:
 zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
zeros.size

10

In [20]:
zeros.shape

(2, 5)

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
rng.shape

(15,)

In [24]:
rng.size

15

In [25]:
rng.dtype

dtype('int64')

In [26]:
lspace = np.linspace(1,5,12)

In [27]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [28]:
emp = np.empty((4, 6))

In [29]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
emp_like = np.empty_like(lspace)

In [31]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [32]:
ide = np.identity(45)

In [33]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [34]:
ide.shape

(45, 45)

In [35]:
ide.size

2025

In [36]:
arr = np.arange(99)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr = arr.reshape(3,33)

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
arr = arr.ravel()

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(99,)

** NumPy Axis **

In [43]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [44]:
ar = np.array(x)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
ar.sum(axis=0)

array([12,  8,  9])

In [47]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [48]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [49]:
ar.flat

In [50]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [51]:
ar.ndim

2

In [52]:
ar.size

9

In [53]:
ar.nbytes

72

In [54]:
print(ar.dtype)


int64


In [55]:
one = np.array([1,3,4,634,2])

In [56]:
print(one.argmax())

3


In [57]:
print(one.argmin())

0


In [58]:
one.argsort()

array([0, 4, 1, 2, 3])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.argmax()

np.int64(6)

In [61]:
ar.argmin()

np.int64(8)

In [62]:
ar.argmax(axis=0)

array([2, 1, 1])

In [63]:
ar.argmax(axis=1)

array([2, 2, 0])

In [64]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [65]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [67]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [69]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
ar2 = np.array([[1, 3, 3],
       [4, 0, 6],
       [7, 1, 0]])

In [72]:
ar + ar2

array([[ 2,  5,  6],
       [ 8,  5, 12],
       [14,  2,  0]])

In [73]:
ar * ar2

array([[ 1,  6,  9],
       [16,  0, 36],
       [49,  1,  0]])

In [74]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [75]:
ar.max()

np.int64(7)

In [76]:
ar.min()

np.int64(0)

In [77]:
ar.sum()

np.int64(29)

In [78]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [79]:
type(np.where(ar>5))

tuple

In [80]:
np.count_nonzero(ar)

8

In [81]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [82]:
ar[1,2] = 0

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [84]:
 import sys

In [85]:
py_ar = [0,4,55,2]

In [86]:
np_ar = np.array(py_ar)

In [87]:
sys.getsizeof(1) * len(py_ar)

112

In [89]:
np_ar.itemsize * np_ar.size

32